server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    try_files /index.html =404;
  }

  location = /maximilian {
    return 301 /maximilian/;
  }

  location = /jantje {
    return 301 /jantje/;
  }

  location = /main {
    return 301 /;
  }

  location /jantje/ {
    try_files $uri $uri/ =404;
  }

  location /maximilian/ {
    try_files $uri $uri/ /maximilian/index.html;
  }

  location / {
    try_files $uri =404;
  }
}
